services:
  # Sucks with ModuleNotFound in root, ditch Flask, embrace FastAPI
  server:
    build: .
    container_name: blackwall-server
    env_file: .env
    command: gunicorn app:"create_flask_app()" -b 0.0.0.0:8000 --reload -k gevent
    ports:
      - 80:8000
    depends_on:
      - redis
  # Works
  redis:
    image: redis:latest
    container_name: blackwall-redis
    ports:
      - 6379:6379
# This breaks SSE, no response from server to client.
#  nginx:
#    container_name: blackwall-nginx
#    image: nginx:latest
#    ports:
#      - 80:80
#    volumes:
#      - ./nginx:/etc/nginx/conf.d
#    depends_on:
#      - server